# XcodeGen Project Specification
# Install XcodeGen: brew install xcodegen
# Generate project: cd Next-track && xcodegen generate

name: Been There
options:
  bundleIdPrefix: com.personal
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: "Been There/Resources/Info.plist"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  Been There:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Been There/App
      - path: Been There/Models
      - path: Been There/Services
      - path: Been There/Views
      - path: Been There/Utilities
      - path: Been There/Resources/Assets.xcassets
      - path: Been There/Resources/Info.plist
        buildPhase: none
      - path: Been There/Resources/Been There.entitlements
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.personal.beenthere
        INFOPLIST_FILE: Been There/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: YES


    entitlements:
      path: Been There/Resources/Been There.entitlements

schemes:
  Been There:
    build:
      targets:
        Been There: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
